# Generated by Django 3.1.7 on 2021-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=800)),
                ('description', models.TextField(max_length=5000)),
                ('averageRating', models.FloatField(default=0)),
                ('image', models.URLField(default=None, null=True)),
            ],
        ),
    ]
